#应用
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  #名称
  name: ecs-console-mobile
  #命名空间
  namespace: ecs-oracle-0514-0824
spec:
  #配置标记k8s1.16必填
  selector:
    matchLabels:
      app: ecs-console-mobile
  #启动应用数量
  replicas: 1
  #从容器启动到应用正常提供服务
  minReadySeconds: 10
  #策略
  strategy:
    #更新类型
    type: RollingUpdate
    #滚动更新
    rollingUpdate:
      #更新时允许最大激增的容器数
      maxSurge: 1
      #更新时允许最大 unavailable 容器数
      maxUnavailable: 0
  #模板
  template:
    #数据描述[元数据]
    metadata:
      #标签
      labels:
        #应用
        app: ecs-console-mobile
        #版本
        version: release200831121811
        #项目端口
        projectPort: p_12357
    #规格
    spec:
      #调度规则,指定部署在指定标签节点中  调度key: 调度值 默认为rancher compute=true标签主机
      nodeSelector:
        51ykb.com:  ecs
      #容器拉取权限
      imagePullSecrets:
        - name : ykb
        - name : aliyun
      #初始化容器
      initContainers:
      - name: install
        image: uhub.service.ucloud.cn/ykb_release/centos:7
        command:
        - "mkdir"
        - "-p"
        - "/data/apache-tomcat-8.5.50/logs/12357/"
        volumeMounts:
        - name: logs
          mountPath: /data/apache-tomcat-8.5.50/logs
      #容器
      containers:
        #名称
      - name: ecs-console-mobile
        #镜像
        image: uhub.service.ucloud.cn/ykb_release/ecs-console-mobile:release200831121811
        #镜像挂载目录
        volumeMounts:
        - name: time
          mountPath: /etc/localtime
        - name: logs
          mountPath: /data/apache-tomcat-8.5.50/logs/12357
          subPath: "12357"
        #计算资源配置
        resources:
          #启动限制
          requests:
            #初始化CPU用量
            cpu: "100m"
            #初始化内存用量
            memory: "2048Mi"
          #最大限制
          limits:
            #限制CPU最大用量
            cpu: "2048m"
            #限制内存最大用量
            memory: "2048Mi"
        #环境变量
        env:
        #堆内存
        - name: heap
        #堆内存值,例子128m
          value: "1228m"
        #存活探针
        livenessProbe:
          #get方式
          httpGet:
            #检测链接
            path: /index.jsp
            #端口
            port: 80
            #方式
            scheme: HTTP
          #初始化
          initialDelaySeconds: 120
          #检测间隔
          periodSeconds: 5
          #超时时间
          timeoutSeconds: 5
          #应用错误判定次数
          failureThreshold: 3
      #实际目录挂载
      volumes:
      #宿主机时间文件
      - name: time
        hostPath:
          path: /etc/localtime
      - name: logs
        nfs:
          server: 10.10.53.143
          path: /
