ALTER TABLE `xinhu_rzgongdi`
ADD COLUMN `id`  int(11) NOT NULL AUTO_INCREMENT AFTER `isturn`,
ADD COLUMN `title`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '项目名称' AFTER `id`,
ADD COLUMN `typeid`  smallint(6) NULL DEFAULT 0 COMMENT '对应分类' AFTER `title`,
ADD COLUMN `num`  varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '编号' AFTER `typeid`,
ADD COLUMN `author`  varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '工长' AFTER `num`,
ADD COLUMN `chuban`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '业主姓名' AFTER `author`,
ADD COLUMN `cbdt`  date NULL DEFAULT NULL COMMENT '出版日期' AFTER `chuban`,
ADD COLUMN `price`  decimal(10,2) NULL DEFAULT 0.00 COMMENT '价格' AFTER `cbdt`,
ADD COLUMN `weizhi`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '存放位置' AFTER `price`,
ADD COLUMN `shul`  smallint(6) NULL DEFAULT 0 COMMENT '数量' AFTER `weizhi`,
ADD COLUMN `adddt`  datetime NULL DEFAULT NULL AFTER `shul`,
ADD COLUMN `optdt`  datetime NULL DEFAULT NULL AFTER `adddt`,
ADD COLUMN `optname`  varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '操作人' AFTER `optdt`,
ADD COLUMN `optid`  smallint(6) NULL DEFAULT 0 AFTER `optname`,
ADD COLUMN `explain`  varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '说明' AFTER `optid`,
ADD COLUMN `isbn`  varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `explain`,
ADD COLUMN `jieshu`  smallint(6) NULL DEFAULT 0 COMMENT '被借阅数' AFTER `isbn`,
ADD COLUMN `uid`  smallint(6) NULL DEFAULT 0 AFTER `jieshu`,
ADD COLUMN `applydt`  date NULL DEFAULT NULL COMMENT '申请日期' AFTER `uid`,
ADD COLUMN `status`  tinyint(1) NULL DEFAULT 1 COMMENT '状态' AFTER `applydt`,
ADD COLUMN `isturn`  tinyint(1) NULL DEFAULT 1 COMMENT '是否提交' AFTER `status`,
ADD COLUMN `courseid`  int(20) NULL DEFAULT NULL COMMENT '当前审核进度' AFTER `isturn`,
ADD COLUMN `coursename`  varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '当前审核进度名称' AFTER `courseid`,
ADD COLUMN `customersource`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '客户来源' AFTER `coursename`,
ADD COLUMN `thirdpro`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '第三方协议' AFTER `customersource`,
ADD COLUMN `telephone`  bigint(11) NULL DEFAULT NULL COMMENT '联系方式' AFTER `thirdpro`,
ADD COLUMN `endtime`  date NULL DEFAULT NULL COMMENT '预计结束时间' AFTER `telephone`,
ADD COLUMN `housesize`  smallint(6) NULL DEFAULT 80 COMMENT '房屋面积' AFTER `endtime`,
ADD COLUMN `housetype`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '房屋类型' AFTER `housesize`,
ADD COLUMN `budgettype`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '预算类型' AFTER `housetype`,
ADD COLUMN `telwatpri`  bigint(10) NULL DEFAULT NULL COMMENT '含水电价' AFTER `budgettype`,
ADD COLUMN `designer`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '设计师' AFTER `telwatpri`,
ADD COLUMN `designerpromise`  varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '设计师承诺' AFTER `designer`,
ADD COLUMN `mdarea`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '门店区域' AFTER `designerpromise`,
ADD COLUMN `nbbh`  varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '内部编号' AFTER `mdarea`,
ADD COLUMN `htys`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '预算员' AFTER `nbbh`,
ADD COLUMN `routelin`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '区域1' AFTER `htys`,
ADD COLUMN `routeline`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '区域' AFTER `routelin`,
ADD COLUMN `yzbrand`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '0' COMMENT '品牌' AFTER `routeline`,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`id`, `id`);

